# Generated by Django 4.2.6 on 2024-03-07 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictec', '0002_estudiante_usuario_alter_calificacion_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='docente',
        ),
    ]
