# Generated by Django 4.2.6 on 2024-03-07 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictec', '0003_remove_estudiante_curso_remove_estudiante_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='carrera',
            field=models.ForeignKey(default=2243, on_delete=django.db.models.deletion.CASCADE, to='dictec.carrera', verbose_name='Carrera'),
            preserve_default=False,
        ),
    ]
