# Generated by Django 4.2.6 on 2024-03-07 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictec', '0004_estudiante_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='carrera',
            field=models.ForeignKey(default=122, on_delete=django.db.models.deletion.CASCADE, to='dictec.carrera', verbose_name='Carrera'),
            preserve_default=False,
        ),
    ]
