# Generated by Django 4.2.6 on 2024-03-07 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictec', '0005_calificacion_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictec.docente', verbose_name='Docente'),
        ),
    ]
