# Generated by Django 4.2.6 on 2024-03-07 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictec', '0006_alter_curso_docente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='apellidos',
        ),
    ]
